name: Generate Playlist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute

jobs:
  update_and_generate_playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install requests

      - name: Update JSON API URLs and generate playlist
        run: |
          python - <<EOF
          import requests
          import json
          import time

          # Define the API URLs
          api_urls = {
              "INA vs VIE": "https://api.gavang.tech/stream/737192e663ca4d1e862b3c80b27a1211/live",
              "IRI vs TKM": "https://api.gavang.tech/stream/cba9c253069c45c78296c9f5e3b3e758/live"
          }

          # Initialize the playlist
          playlist = "#EXTM3U\n"

          while True:
              try:
                  # Iterate over each API URL
                  for channel_name, api_url in api_urls.items():
                      try:
                          # Fetch data from the API
                          response = requests.get(api_url)
                          response.raise_for_status()  # Raise an exception for non-200 status codes
                          data = response.json()
                          
                          # Get the .m3u8 URL for the respective channel
                          m3u8_url = data.get("data", {}).get("hd_1")
                          
                          # If data is available, add it to the playlist
                          if m3u8_url:
                              playlist += f"#EXTINF:-1,{channel_name}\n{m3u8_url}\n"
                          else:
                              print(f"No .m3u8 URL found for {channel_name}")
                      except Exception as e:
                          print(f"Error fetching data from {api_url}: {e}")

                  # Write the playlist to a file if there's any data
                  if len(playlist) > len("#EXTM3U\n"):
                      with open("playlist.m3u", "w") as file:
                          file.write(playlist)
                      print("Playlist created successfully!")
                  else:
                      print("No data available to generate playlist.")

                  # Wait for 1 minute before checking again
                  time.sleep(60)
              except Exception as e:
                  print(f"Error updating API URLs and generating playlist: {e}")
                  exit(1)
          EOF

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Update playlist.m3u"
          git push || true  # Ignore error if there are no changes to commit
