name: Generate, Delete, and Output Playlist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/3 * * * *'  # Runs every 3 minutes

jobs:
  update_and_generate_playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install requests

      - name: Update JSON API URLs and generate playlist
        run: |
          python - <<EOF
          import requests
          import json
          import os

          try:
              # Define the API URLs
              api_urls = {
              "Live1": "https://goaltv.cloudns.org/livestream/04.json",
                  "INA vs VIE": "https://api.gavang.tech/stream/737192e663ca4d1e862b3c80b27a1211/live",
                  "IRI vs TKM": "https://api.gavang.tech/stream/cba9c253069c45c78296c9f5e3b3e758/live"
              }

              # Initialize the playlist
              playlist = "#EXTM3U\n"

              # Iterate over each API URL
              for channel_name, api_url in api_urls.items():
                  try:
                      # Fetch data from the API
                      response = requests.get(api_url)
                      response.raise_for_status()  # Raise an exception for non-200 status codes
                      data = response.json()
                      
                      # Get the .m3u8 URL for the respective channel
                      m3u8_url = data.get("data", {}).get("hd_1")
                      
                      # Add the entry to the playlist
                      if m3u8_url:
                          playlist += f"#EXTINF:-1,{channel_name}\n{m3u8_url}\n"
                      else:
                          print(f"No .m3u8 URL found for {channel_name}")
                  except Exception as e:
                      print(f"Error fetching data from {api_url}: {e}")

              # Add existing .m3u8 URLs
              playlist += "#EXTINF:-1,MRTV-4 HD\nhttps://ppradio.b-cdn.net/LiveApp/streams/w3g3EYjBtqgJ1677679288037.m3u8\n"
              playlist += "#EXTINF:-1,MRTV-4 SD\nhttps://5a13fe32ef748.streamlock.net/mmplay/mrtv-4/chunklist_w749853444.m3u8\n"

              # Write the playlist to a file
              with open("playlist.m3u", "w") as file:
                  file.write(playlist)

              print("Playlist created successfully!")
          except Exception as e:
              print(f"Error updating API URLs and generating playlist: {e}")
              exit(1)

          try:
              # Output the playlist contents
              print("Playlist contents:")
              with open("playlist.m3u", "r") as file:
                  print(file.read())
              
              # Delete the playlist file after output
              os.remove("playlist.m3u")
              print("Playlist deleted successfully!")
          except Exception as e:
              print(f"Error deleting playlist file: {e}")
              exit(1)
          EOF

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update playlist.m3u"
          git push
